version: '3'
services:
  local-llm:
    build:
      context: .
      dockerfile: Dockerfile.real
    ports:
      - "7860:7860"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 4G  # Adjust based on your system's capabilities